coverage:
  status:
    project: off
    patch: off
    all:
      flags: all
    gui:
      flags: gui
    tests:
      flags: tests

flags:
  gui:
    paths:
      - src/gui
  tests:
    paths:
      - src/test

codecov:
  ci:
    - symboxtra.dynu.net/jenkins

ignore:
    - "src/libs/"
    - "qt/"
    - "**/main.cpp"
