language: cpp

matrix:
    include:
        - os: osx
          compiler: clang
          osx_image: xcode9.2
        - os: linux
          compiler: gcc
          addons:
            apt:
                update: true

git:
    depth: 1 # Limit unneeded commit depth
    submodules: false

before_install:
    - set -o pipefail
    - git submodule update --init --recursive

install:
    - |
        if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
            brew update
            brew install qt
            brew install lcov
            brew install boost
            export PATH=/usr/local/opt/qt/bin:${PATH}
        fi
    - |
        if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
            sudo apt install lcov

            # Download Qt 5.10.1
            echo
            echo "Downloading Qt..."
            curl -L https://www.dropbox.com/s/f1xo8wbypvax9hr/qt-portable-ubuntu-16.04-v2.tar.gz?dl=1 -o $HOME/qt-portable-ubuntu-16.04-v2.tar.gz
            mkdir $HOME/qt
            tar -xzf $HOME/qt-portable-ubuntu-16.04-v2.tar.gz -C $HOME/qt --strip-components 1

            export PATH=$HOME/qt/5.10.1/gcc_64/bin:${PATH}
            export LD_LIBRARY_PATH=$HOME/qt/5.10.1/gcc_64/lib
            export QT_PLUGIN_PATH=$HOME/qt/5.10.1/gcc_64/plugins
            export QML_IMPORT_PATH=$HOME/qt/5.10.1/gcc_64/qml
            export QML2_IMPORT_PATH=$HOME/qt/5.10.1/gcc_64/qml
            export QT_DEBUG_PLUGINS=1
            export QT_IMPORT_TRACE=1

            qmake -v
            echo "Installed Qt 5.10.1"

            sudo apt install libboost-all-dev
        fi

before_script:
    - mkdir build
    - cd build
    - cmake ..
    - cd ..

script:
    - ./test.sh

after_success:
    - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports" # Collect coverage data
    - curl https://raw.githubusercontent.com/symboxtra/travis-ci-discord-webhook/master/send.sh > send.sh && chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL # Webhook to Discord

after_failure:
    - curl https://raw.githubusercontent.com/symboxtra/travis-ci-discord-webhook/master/send.sh > send.sh && chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL # Webhook to Discord
