language: cpp

matrix:
    include:
        - os: osx
          compiler: clang
          osx_image: xcode9.2
        - os: linux
          compiler: gcc

git:
    depth: 1 # Limit unneeded commit depth
    submodules: false

before_install:
    - set -o pipefail
    - git submodule update --init --recursive

install:
    - |
        if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
            brew update
            brew install qt
            brew install lcov
            PATH=/usr/local/opt/qt/bin:${PATH}
        fi
    - |
        if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
            sudo apt update
            sudo apt install lcov

            # Download Qt 5.10.1
            echo -e "machine github.com\n login $GITHUB_TOKEN" >> ~/.netrc # Authenticate to pull private repo and access Git LFS
            GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/jmcker/qt-portable # Private
            echo "Smudge skipped" # Test if smudge is skipped
            cd qt-portable
            git lfs pull
            mkdir ../qt
            tar -xzf qt-portable-ubuntu-16.04.tar.gz -C ../qt --strip-components 1
            cd ..
            PATH=$PWD/qt/bin:${PATH}
        fi

before_script:
    - mkdir build
    - cd build
    - cmake ..
    - cd ..

script:
    - ./test.sh

after_success:
    - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports" # Collect coverage data
    - curl https://raw.githubusercontent.com/symboxtra/travis-ci-discord-webhook/master/send.sh > send.sh && chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL # Webhook to Discord

after_failure:
    - curl https://raw.githubusercontent.com/symboxtra/travis-ci-discord-webhook/master/send.sh > send.sh && chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL # Webhook to Discord
