image: Visual Studio 2017

environment:
    matrix:
    - QT: C:\Qt\5.10.1\msvc2017_64
      PLATFORM: amd64
      COMPILER: msvc
      VSVER: 14

clone_depth: 1

init:
    - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

install:
    - git submodule update --init --recursive
    - ps: .\installOpenCppCoverage.ps1

build_script:
    - ps: $env:QTDIR = "C:\Qt\5.10.1\msvc2017_64\lib\cmake\Qt5"
    - ps: .\test.ps1

on_success:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/symboxtra/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 success $env:WEBHOOK_URL # Discord Webhook
    - ps: |
        Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
        bash codecov.sh -f "cobertura.xml"

on_failure:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/symboxtra/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 failure $env:WEBHOOK_URL # Discord Webhook
