image: Visual Studio 2017

environment:
    matrix:
    - QT: C:\Qt\5.10.1\msvc2017_64
      PLATFORM: am64
      COMPILER: msvc
      VSVER: 14

notifications:
    - provider: Webhook
      url: https://discordapp.com/api/webhooks/436971095208230922/De0x0wc8iZ6WzMMTzyWn7doVC9RhFzimCB4VwLUzqAhEXxBkIqb0B-qlyRdqOQMQ-88f
      method: POST
      on_build_success: true
      on_build_failure: true
      on_build_status_changed: true
clone_depth: 1

init:
    - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

install:
    - git submodule update --init --recursive

build_script:
    - ps: $env:QTDIR = "C:\Qt\5.10.1\msvc2017_64\lib\cmake\Qt5"
    - ps: .\test.ps1

