image: Visual Studio 2017

environment:
    matrix:
    - QT: C:\Qt\5.10.1\msvc2017_64
      PLATFORM: am64
      COMPILER: msvc
      VSVER: 14

clone_depth: 1

init:
    - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

build_script:
    - ps: .\test.ps1
